# generated by datamodel-codegen:
#   filename:  default.json

from __future__ import annotations

from pydantic import BaseModel
from pydantic import Extra


class SetItem(BaseModel):
    class Config:
        extra = Extra.forbid

    string_0: str
    bytes: str
    string_1: str


class DefaultParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    set: list[SetItem]
    bool: bool
