# Run `dipdup new --replay configs/replay.yaml` to generate new project from this replay
spec_version: 2.0
replay:
  dipdup_version: 7
  template: demo_blank
  package: tzprofiles
  version: 0.0.1
  description: DipDup indexer for Tezos Profiles
  license: Apache 2.0
  name: Spruce Systems, Inc.
  email: 
  postgresql_image: postgres:15
  hasura_image: hasura/graphql-engine:v2.30.0
  line_length: 120
