spec_version: 1.1
package: tzprofiles_indexer

database:
  kind: sqlite
  path: tzprofiles.sqlite3

contracts:
  tzprofile_old:
    address: KT1KsmdYxuJHCMqLRX1PH7JJeXvXaMeicEa7
    typename: tzprofile
  tzprofile:
    address: KT1G6jaUQkRcxJcnrNLjCTn7xgD686PM2mEd
    typename: tzprofile

datasources:
  tzkt:
    kind: tzkt
    url: https://pro.tzkt.io/tmp

templates:
  tzprofiles:
    kind: operation
    datasource: tzkt
    contracts:
      - <contract>
    types:
      - transaction
      - origination
    handlers:
      - callback: on_origination
        pattern:
          - type: origination
            originated_contract: <contract>
      - callback: on_update
        pattern:
          - destination: <contract>
            entrypoint: default

indexes:
  factory:
    kind: operation
    datasource: tzkt
    types:
      - origination
    handlers:
      - callback: on_factory_origination
        pattern:
          - type: origination
            similar_to: tzprofile
      - callback: on_factory_origination
        pattern:
          - type: origination
            similar_to: tzprofile_old
    stateless: True
    subscribe_by_entrypoints: True

jobs:
  fetch_claims:
    callback: fetch_claims
    interval: 5
    atomic: False

sentry:
  dsn: https://27d26eb33f1b4633852c2a0e9855bd3a@sentry.baking-bad.org/9
  environment: local
  debug: true
