# Run `dipdup new --replay configs/replay.yaml` to generate new project from this replay
spec_version: 2.0
replay:
  dipdup_version: 7
  template: demo_blank
  package: tzprofiles_indexer
  version: 0.0.1
  description: Tezos Profiles (TZP) is a web application that helps users regain control 
  license: Apache 2.0
  name: 
  email: 
  postgresql_image: postgres:15
  hasura_image: hasura/graphql-engine:v2.30.0
  line_length: 120
